repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
      - id: nbstripout
        name: nbstripout
        description: 'nbstripout: strip output from Jupyter and IPython notebooks'
        entry: nbstripout
        language: python
        types: [jupyter]
  - repo: https://github.com/tomcatling/black-nb
    rev: "0.7"
    hooks:
      - id: black-nb
        description: strip output and black source
        additional_dependencies: ['black[jupyter]']
        args: ["--clear-output"]
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
    - id: black
